enabled_features = ["ping", "say", "version", "test_checks", "utils", "testing", "question_day"]

[features]
[features.say]
ephemeral_default = true

[features.utils]
ephemeral_default = true
guild_id=1218400838196662403